# Server Configuration
server.port=${PORT:8080}
server.servlet.context-path=

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:scan2dine}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:hari@2509}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Settings
scan2dine.jwt.secret=9a67a86c75324e93bb8d2b0e9b88cf1e54911d5e68374d6f8cf9c34f501258ab
scan2dine.jwt.expiration-ms=86400000

# Swagger / OpenAPI Properties
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha

# File Upload configuration (Optional, for logo uploads)
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
